#!/bin/sh

CURDIR=`dirname "$0"`
cd "$CURDIR"
VERSION="0.68"

SOURCE_PACKAGE="pdf2json-$VERSION.tar.gz"
WIN32_BIN_PACKAGE="pdf2json-$VERSION-win32.zip"
EXTRACTED="pdf2json-$VERSION"
TARGET_DIR="../inc/" # relative to $CURDIR
wget -P "$TARGET_DIR" -c \
	https://pdf2json.googlecode.com/files/"$SOURCE_PACKAGE" \
	https://pdf2json.googlecode.com/files/"$WIN32_BIN_PACKAGE"
